# Generated by Django 2.0.6 on 2018-07-07 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0004_auto_20180707_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskentry',
            name='Task_dependant',
            field=models.ForeignKey(blank=True, default='NULL', null=True, on_delete=django.db.models.deletion.CASCADE, to='Task.TaskEntry'),
        ),
    ]
