# Generated by Django 2.0.6 on 2018-07-16 06:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0008_auto_20180708_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskentry',
            name='Task_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
