# Generated by Django 2.0.6 on 2018-07-16 07:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0010_auto_20180716_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskentry',
            name='Task_create',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 16, 7, 44, 17, 289990, tzinfo=utc)),
        ),
    ]
