# Generated by Django 2.0.6 on 2018-07-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0011_auto_20180716_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskentry',
            name='Task_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
