# Generated by Django 2.0.6 on 2018-07-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0012_auto_20180716_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskentry',
            name='Task_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
